kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-rust-btc-full-node
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 640Gi
  storageClassName: io1